Adds performance tests
AmadeusW/VSEmbed pull request #31
Opened 2017-01-19 19:52 UTC by AmadeusW

This PR brings the following tests:
* `CutCopyUndoPasteTest` - Cut, Copy, Paste, Undo
* `AutoformattingTest` - Autoformatting and smart indent on semicolon
* `BraceCompletionTest` - Autoformatting on closing brace
* `BasicTypingTest` 
 * Typing within a comment (doesn't trigger auto formatting)
 * Typing in a large file

Also updates .gitignore, it changed since Shabse last committed it.

2017-01-23 23:27 UTC, JoshVarty requested changes

2017-01-23 23:27 UTC, JoshVarty commented on PerformanceTests/DiagnosticApplication.cs
> +		internal static void Run(TestBase testClass, Action testMethod = null, bool clean = false)
I think we can remove `clean` it appears never to be passed in as `true`.

2017-01-23 23:27 UTC, JoshVarty commented on PerformanceTests/Props/Snippets.cs
> +				case Location.OutsideNamespace:
Can you add a comment stating where each location is? (eg. "Before first using", "Before the `class` keyword" etc.)

2017-01-23 23:27 UTC, JoshVarty commented on PerformanceTests/TestBase.cs
> +		public virtual void SetupHost()
Does any test **not** override `SetupHost()`? Consider making it abstract if not.

2017-01-24 00:10 UTC, AmadeusW commented on PerformanceTests/Props/Snippets.cs
> +				case Location.OutsideNamespace:
good idea! Done

2017-01-24 00:11 UTC, AmadeusW commented on PerformanceTests/TestBase.cs
> +		public virtual void SetupHost()
they all do, but `SetupHost` has a body and cannot be marked abstract.

2017-01-24 00:18 UTC, JoshVarty approved these changes

2017-01-24 00:18 UTC, merged