Focused typing test
AmadeusW/VSEmbed pull request #32
Opened 2017-01-24 22:12 UTC by AmadeusW

Simplifies TestBase (turns a public virtual into protected abstract)
Introduces a focused typing test that can be invoked multiple times

2017-01-24 22:15 UTC, JoshVarty requested changes

2017-01-24 22:15 UTC, JoshVarty commented on PerformanceTests/DiagnosticApplication.cs
> +			//for (int i = 0; i < 10; i++)
Do we need this?

2017-01-24 22:48 UTC, AmadeusW commented on PerformanceTests/DiagnosticApplication.cs
> +			//for (int i = 0; i < 10; i++)
Some tests can be ran multiple times. I added a comment, and added another debug-time line

2017-01-25 00:30 UTC, JoshVarty approved these changes

2017-01-25 00:30 UTC, merged